### PR TITLE
Russian language + icons

### PR DESCRIPTION
**Pull request by quarkov**

### CODE REVIEW

**Comment by kurosawa4434** [comment]
Thanks @quarkov  :D
This icon is very cool.
BTW,
I don't know how CheckiO applies mission icons.
I would like to design my mission icon in the future.
What should I do?

**Comment by quarkov** [comment]
Sorry for a late reply @kurosawa4434 
I'm glad you liked the icons. 
Now regarding how CiO applies them. 
They should be applied manually by any  of CiO admins.
So just put your icons into the "logo" folder (.png format, 1200x1200 px) and then they will be used.

**Comment by kurosawa4434** [comment]
Thanks @quarkov . I got it.
If I prepared the icons myself, I would have to tell them in forum.

You are posting the icon with SVG format. Why ? :-)

**Comment by quarkov** [comment]
Vector graphics is better than raster graphics, you can work with vector images as with a group of objects, that gives you an ability to adjust any of the objects easily if it's necessary to correct the design.
Plus you can scale a vector image without a compression/extension artifact appearance.  
   
Before being applied, icons need to be converted into .png though.

**Comment by kurosawa4434** [comment]
Thanks again @quarkov !

On another note,
The icon of Mission "Boundary Blocks" has problem.
https://py.checkio.org/forum/post/13201/new-mission-boundary-blocks/#comment-75384
Could you help me ?

**Comment by quarkov** [comment]
Dear @kurosawa4434 , sorry for a late reply, I was off for a couple of days.
For now I don't have an answer whether I could help or not, within the next day I will come up with something. BTW, if you're using telegram app, you can reach me there directly if you wish, search for @quarkov  =)

**Comment by quarkov** [comment]
@kurosawa4434 
So I asked oduvan about those icons and he told me that you could propose new icons. 
Put them into the mission repo and let me know somehow, I'll review them quickly and upload if everything is ok. Does work for you?

**Comment by kurosawa4434** [comment]
I understand.
I will make the icon myself form now.
Thank you :-D

**Pull request merged**
